# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-24 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='char_user',
        ),
        migrations.RemoveField(
            model_name='image',
            name='img',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='item_char',
        ),
        migrations.AddField(
            model_name='character',
            name='gold',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
