# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-26 17:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_auto_20180725_0405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.RemoveField(
            model_name='image',
            name='img_char',
        ),
        migrations.AddField(
            model_name='image',
            name='img',
            field=models.ImageField(blank=True, default='default.pmg', upload_to=''),
        ),
        migrations.AddField(
            model_name='image',
            name='img_mon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mon_img', to='first_app.Monster'),
            preserve_default=False,
        ),
    ]
